const std = @import("std");
const preset = @import("preset").preset;
const ChainConfig = @import("../chain_config.zig").ChainConfig;
const BlobScheduleEntry = @import("../chain_config.zig").BlobScheduleEntry;
const b = @import("../../root.zig").hexToBytesComptime;

const mainnet = @import("./mainnet.zig").mainnet_chain_config;

// all values are placeholders with mainnet and need to be filled in with actual values
pub const hoodi_chain_config = ChainConfig{
    .PRESET_BASE = mainnet.PRESET_BASE,
    .CONFIG_NAME = "hoodi",

    // Transition
    .TERMINAL_TOTAL_DIFFICULTY = 0,
    .TERMINAL_BLOCK_HASH = mainnet.TERMINAL_BLOCK_HASH,
    .TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH = mainnet.TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH,

    // Genesis
    .MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = mainnet.MIN_GENESIS_ACTIVE_VALIDATOR_COUNT,
    .MIN_GENESIS_TIME = 1742212800,
    .GENESIS_FORK_VERSION = b(4, "0x10000910"),
    .GENESIS_DELAY = 600,

    // Forking
    // Atair
    .ALTAIR_FORK_VERSION = b(4, "0x20000910"),
    .ALTAIR_FORK_EPOCH = 0,
    // Bellatrix
    .BELLATRIX_FORK_VERSION = b(4, "0x30000910"),
    .BELLATRIX_FORK_EPOCH = 0,
    // Capella
    .CAPELLA_FORK_VERSION = b(4, "0x40000910"),
    .CAPELLA_FORK_EPOCH = 0,
    // Deneb
    .DENEB_FORK_VERSION = b(4, "0x50000910"),
    .DENEB_FORK_EPOCH = 0,
    // Electra
    .ELECTRA_FORK_VERSION = b(4, "0x60000910"),
    .ELECTRA_FORK_EPOCH = 2048,
    // Fulu
    .FULU_FORK_VERSION = b(4, "0x70000910"),
    .FULU_FORK_EPOCH = std.math.maxInt(u64),

    // Time parameters
    .SECONDS_PER_SLOT = mainnet.SECONDS_PER_SLOT,
    .SECONDS_PER_ETH1_BLOCK = 12,
    .MIN_VALIDATOR_WITHDRAWABILITY_DELAY = mainnet.MIN_VALIDATOR_WITHDRAWABILITY_DELAY,
    .SHARD_COMMITTEE_PERIOD = mainnet.SHARD_COMMITTEE_PERIOD,
    .ETH1_FOLLOW_DISTANCE = mainnet.ETH1_FOLLOW_DISTANCE,

    // Validator cycle
    .INACTIVITY_SCORE_BIAS = mainnet.INACTIVITY_SCORE_BIAS,
    .INACTIVITY_SCORE_RECOVERY_RATE = mainnet.INACTIVITY_SCORE_RECOVERY_RATE,
    .EJECTION_BALANCE = mainnet.EJECTION_BALANCE,
    .MIN_PER_EPOCH_CHURN_LIMIT = mainnet.MIN_PER_EPOCH_CHURN_LIMIT,
    .MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT = mainnet.MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT,
    .CHURN_LIMIT_QUOTIENT = mainnet.CHURN_LIMIT_QUOTIENT,
    .MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT = mainnet.MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT,
    .MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA = mainnet.MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA,

    // Fork choice
    .PROPOSER_SCORE_BOOST = mainnet.PROPOSER_SCORE_BOOST,
    .REORG_HEAD_WEIGHT_THRESHOLD = mainnet.REORG_HEAD_WEIGHT_THRESHOLD,
    .REORG_PARENT_WEIGHT_THRESHOLD = mainnet.REORG_PARENT_WEIGHT_THRESHOLD,
    .REORG_MAX_EPOCHS_SINCE_FINALIZATION = mainnet.REORG_MAX_EPOCHS_SINCE_FINALIZATION,

    // Deposit contract
    .DEPOSIT_CHAIN_ID = 560048,
    .DEPOSIT_NETWORK_ID = 560048,
    .DEPOSIT_CONTRACT_ADDRESS = mainnet.DEPOSIT_CONTRACT_ADDRESS,

    // Networking
    .MIN_EPOCHS_FOR_BLOCK_REQUESTS = mainnet.MIN_EPOCHS_FOR_BLOCK_REQUESTS,
    .MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS = mainnet.MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS,
    .BLOB_SIDECAR_SUBNET_COUNT = mainnet.BLOB_SIDECAR_SUBNET_COUNT,
    .MAX_BLOBS_PER_BLOCK = mainnet.MAX_BLOBS_PER_BLOCK,
    .MAX_REQUEST_BLOB_SIDECARS = mainnet.MAX_REQUEST_BLOB_SIDECARS,
    .BLOB_SIDECAR_SUBNET_COUNT_ELECTRA = mainnet.BLOB_SIDECAR_SUBNET_COUNT_ELECTRA,
    .MAX_BLOBS_PER_BLOCK_ELECTRA = mainnet.MAX_BLOBS_PER_BLOCK_ELECTRA,
    .MAX_REQUEST_BLOB_SIDECARS_ELECTRA = mainnet.MAX_REQUEST_BLOB_SIDECARS_ELECTRA,
    .MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS = mainnet.MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS,

    .SAMPLES_PER_SLOT = mainnet.SAMPLES_PER_SLOT,
    .CUSTODY_REQUIREMENT = mainnet.CUSTODY_REQUIREMENT,
    .NODE_CUSTODY_REQUIREMENT = mainnet.NODE_CUSTODY_REQUIREMENT,
    .VALIDATOR_CUSTODY_REQUIREMENT = mainnet.VALIDATOR_CUSTODY_REQUIREMENT,
    .BALANCE_PER_ADDITIONAL_CUSTODY_GROUP = mainnet.BALANCE_PER_ADDITIONAL_CUSTODY_GROUP,

    // Blob Scheduling
    .BLOB_SCHEDULE = &[_]BlobScheduleEntry{},
};
