pub const OperationsTestHandler = enum(u8) {
    attestation,
    attester_slashing,
    block_header,
    deposit,
    proposer_slashing,
    voluntary_exit,
    sync_aggregate,
    execution_payload,
    withdrawals,
    bls_to_execution_change,
    deposit_request,
    withdrawal_request,
    consolidation_request,
};
