// This file is generated by write_spec_tests.zig.
// Do not commit changes by hand.

const testing = @import("std").testing;

comptime {
     testing.refAllDecls(@import("./test_case/operations_tests.zig"));
}
