// TODO: For each test type, add header and test case code
const std = @import("std");

pub const OPERATIONS_HEADER =
    \\// This file is generated by write_static_tests.zig.
    \\// Do not commit changes by hand.
    \\
    \\const std = @import("std");
    \\const spec_test_options = @import("spec_test_options");
    \\const build_options = @import("build_options");
    \\const types = @import("consensus_types");
    \\const test_case = @import("test_case.zig");
    \\
    \\const allocator = std.testing.allocator;
    \\
    \\
;

pub const OPERATIONS_TEST_TEMPLATE =
    \\test "Static - {s} {s} {s} {s}" {{
    \\    const test_dir_name = try std.fs.path.join(allocator, {s});
    \\    defer allocator.free(test_dir_name);
    \\
    \\    const test_dir = std.fs.cwd().openDir(test_dir_name, .{{}}) catch return error.SkipZigTest;
    \\    try test_case.validTestCase(types.{s}.{s}, allocator, test_dir, "roots.yaml");
    \\}}
    \\
    \\
;
